# Generated by Django 5.0.1 on 2024-01-18 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='bairro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bairro_do_imovel', to='plataforma.bairro'),
        ),
    ]
